apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
  namespace: node-k8s
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: floriaaan/node_k8s_api:1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: db_host
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: db_pass
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: db_name
            - name: DB_DAILECT
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: db_dialect
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: db_port
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: access_token_secret
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: refresh_token_secret
            - name: ACCESS_TOKEN_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: access_token_expiry
            - name: REFRESH_TOKEN_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: refresh_token_expiry
            - name: REFRESH_TOKEN_COOKIE_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: refresh_token_cookie_name

          ports:
            - containerPort: 3000
