apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: node-k8s
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: floriaaan/node_k8s_api:1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: PORT
              value: "3000"
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "YOUR_POSTGRES_PASSWORD"
            - name: DB_DATABASE
              value: "postgres"
            - name: DB_DAILECT
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: ACCESS_TOKEN_SECRET
              value: "YOUR_SECRET_KEY"
            - name: REFRESH_TOKEN_SECRET
              value: "YOUR_SECRET_KEY"
            - name: ACCESS_TOKEN_EXPIRY
              value: "15m"
            - name: REFRESH_TOKEN_EXPIRY
              value: "7d"
            - name: REFRESH_TOKEN_COOKIE_NAME
              value: "jid"

          ports:
            - containerPort: 3000
