apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: node-k8s
  labels:
    app: api
type: Opaque
data:
    db_user: dXNlcg==
    db_pass: cGFzcw==
    access_token_secret: c2VjcmV0
    refresh_token_secret: c2VjcmV0